#local file ~/Ansible_playbooks/app_production_playbook.yml
---
 #Hostname of your application server, (or group if you are deploying to multiple)
 - hosts: phinitive
   user: root
   vars:
     #repo containing your project
     gitrepo: https://github.com/unknownexception/philosoraptor.git
     #Destination directory
     gitdest: /home/philosoraptor/src
     #Desired git branch
     gitbranch: master
     #docker image
     dockerimage: unknownexception/raptor

   tasks:
   - name: Git Checkout current Branch
     git: repo={{gitrepo}}
          dest={{gitdest}}
          version={{gitbranch}}


   - name: Cleanup previous docker builds
     shell: "docker ps -a | grep 'Exit' |  awk '{print $1}' | xargs docker rm &> /dev/null &"

   - name: Cleanup previous docker images
     shell: "docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &"

   - name: Change directory to source
     shell: cd {{gitdest}}

   - name: Build docker image
     script: start.sh chroot={{gitdest}}
