twitter:
  consumer_key: "VE7fixgfdaswpvPBlsKuw"
  consumer_secret: "LPSfhVgSA0lFqVC2tHRxVdagzI4csS1rSbFi0gJbL68"
  access_token_key: "1629668064-FWmO5QpI6QbuCkbtU1L4s7wi1iTVKoAWMPA4VPB"
  access_token_secret: "q7djQdCJN8ApJeM3yqk06b2Iyt0fFPNoN8tP19kZilcIz"
bing:
  client_id: "philosophoraptor"
  client_secret: "J8G078YXhuODZ1NSpIy/7h0agazoWleK6vHy7PG7RWQ="
instagram:
  client_id: "34d2554d05cb4bf4981865b2c3cd9c75"
  client_secret: "fc5d40c2d453414989caeacccfdbc60f"
google:
  api_key: "AIzaSyCnT_7lG2mupK-Xz62QcMUyc7xIUYnaNqM"
  cx: "008572512467937060619:rngfda__7-k"